### ISSUE TITLE
Is there a gradle version of the tailwind setup discussed in the book.

### ISSUE THREAD

**Issue by calebgrimah** [wimdeblauwe/taming-thymeleaf-sources#2]
Hello, can you help provide a gradle version of setting up tailwind and other dependencies for the project.

**Comment by wimdeblauwe** [comment]
Hi, I am not using Gradle, so I don't have this. There is this blog post that might help you: https://www.schuehly-it.de/posts/spring-boot-thymeleaf-livereload-gradle/

**Comment by grey-shirt** [comment]
Hi all, 👋

A bit late now I suppose but hopefully this will help someone in the future! 

I've made a [Gradle template repo](https://github.com/grey-shirt/thymeleaf-tailwind-gradle-template) which has Thymeleaf and Tailwind setup. 🙂

**Comment by wimdeblauwe** [comment]
Thank you for that @grey-shirt !
