### ISSUE TITLE
Deprecated unwrapped fragment expression

### ISSUE THREAD

**Issue by marcfargas** [wimdeblauwe/taming-thymeleaf-sources#4]
Hi,

I'm currently reading the latest version of the book, and enjoying it so far!!

My console just got full of ugly complaints from Thymeleaf, using Spring Boot 3.0.5 during Chapter 05 I get:

```
actStandardFragmentInsertionTagProcessor : Deprecated unwrapped fragment expression "fragments/sidebar-menu :: mobile" found in template index, line 19, col 10. Please use the complete syntax of fragment expressions instead ("~{fragments/sidebar-menu :: mobile}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
```

This happens with all uses of fragments in Chapter 05, all `th:replace` uses need this ugly "complete syntax" (wrap the current value within `~{}`.

**Comment by marcfargas** [comment]
The same happens with `<svg th:replace="~{${icon}}"></svg>`

**Comment by wimdeblauwe** [comment]
Thanks for letting me know. I had to to this update in multiple places, seems I forgot in some. Thanks for letting me know!
