### ISSUE TITLE
Odd code listing page 124

### ISSUE THREAD

**Issue by marcfargas** [wimdeblauwe/taming-thymeleaf-sources#5]
Hi,

This is not about the code listed here exactly, but an odd listing on the book. I report here for convenience:

On page 124 there's a code listing to introduce `@ActiveProfiles` and `@AutoConfigureTestDatabase` annotations. But the listing appears to be wrong.

The listing displayed is the same as on page 121 (even the bullet numbers that go up to 9). Below the listing the explanation talks about those annotations and explains 4 things (not 9 as show in the listing).

On this repository the code is correct: https://github.com/wimdeblauwe/taming-thymeleaf-sources/blob/d1d8fd88ce97d5ff4866123ae4049a0a964be122/chapter09/src/test/java/com/tamingthymeleaf/application/user/UserRepositoryTest.java#L24-L25

(version 3.0.0, 2023-03-31, PDF)

![image](https://user-images.githubusercontent.com/10505/233782312-cd3d3a72-73d2-48fa-894f-e9473a51f61f.png)

![image](https://user-images.githubusercontent.com/10505/233782318-1aa98c27-b713-4d00-8a18-2674771cd48b.png)

**Comment by wimdeblauwe** [comment]
New version of the book released on leanpub that fixes this. Thanks for letting me know!
