### ISSUE TITLE
Feature request: Implement "Forgot Password" functionality

### ISSUE THREAD

**Issue by LiveNathan** [wimdeblauwe/taming-thymeleaf-sources#6]
The link is there on the login form, just doesn't go anywhere. :)

**Comment by wimdeblauwe** [comment]
It is just there because it is part of the Tailwind UI template I used. I never had the intention to implement it. Let's say I left it as an exercise for the reader :-)

**Comment by LiveNathan** [comment]
Makes sense. Took me a bit, but I figured it out.
