### ISSUE TITLE
org.springframework.web.servlet.support.ServletUriComponentsBuilder not accessible in latest Thymeleaf

### ISSUE THREAD

**Issue by wlfshmn** [wimdeblauwe/taming-thymeleaf-sources#7]
The pagination examples are broken with thymeleaf 3.1.2, which is pulled in starting with Srping Boot 3.0.10, and 3.1.3.

**Comment by wlfshmn** [comment]
https://github.com/thymeleaf/thymeleaf/commit/dd01397c785d7d34049eecd67440aef52398599d for reference

**Comment by wimdeblauwe** [comment]
Thank you very much for letting me know about this. I have opened https://github.com/thymeleaf/thymeleaf/issues/977 to further understand how to proceed with the new Thymeleaf version. In the mean time, you can use Spring Boot 3.0.9 which still works.

**Comment by wlfshmn** [comment]
Only the instantiation seems to be blocked, calling on the instantiated object has no class limitation as of now. A simple wrapper  like the following works (for now):

```package com.tamingthymeleaf.application.infrastructure.web;

import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

public class ServletUriComponentsBuilderWrapper {

  public static ServletUriComponentsBuilder fromCurrentRequest() {
    return ServletUriComponentsBuilder.fromCurrentRequest();
  }
}
```
The limitaiton may have been for a valid reason though, which isn't addressed by this, but if anyone feels stuck, it's a quick-fix.

**Comment by wimdeblauwe** [comment]
I fixed it in a slightly different way.

Add the following bean declaration to `com.tamingthymeleaf.application.infrastructure.webWebMvcConfiguration`:

```
    @Bean
    @RequestScope
    public ServletUriComponentsBuilder urlBuilder() {
        return ServletUriComponentsBuilder.fromCurrentRequest();
    }
```

Then in the Thymeleaf template `pagination.html`, replace `urlBuilder.fromCurrentRequest()` with `@urlBuilder`. See the linked commit for more details.
